function [pattern] = generate_barrelettes(rates,shuf)

% Assigns the rates to positions in the matrix (shuf), i.e generated by the
% function shuffle, such that neurons for each whisker are randomly assigned
% to a square sub-region of the barrelette map

r = size(rates);
N_neurons = r(1);
time = 1;
N_whiskers = r(2);

w = sqrt(N_whiskers);
n = sqrt(N_neurons);

pattern = zeros(n*w,n*w,time);


% if shuffle is not being used then project rates to their ordinal reshape co-ordinate
if shuf ==0

    for x = 1:w
        for y = 1:w
            pattern(((x-1)*n)+1:((x-1)*n)+n,((y-1)*n)+1:((y-1)*n)+n) = reshape(rates(:,((x-1)*w)+y),n,n)';
        end
    end

    % if shuffle is being used then rates are sent to a random co-ordinate
else

    shuf_rates = zeros(1,N_neurons);

    for x = 1:w
        for y = 1:w
            for i = 1:N_neurons
                shuf_rates(i) = rates(shuf(((x-1)*w)+y,i),((x-1)*w)+y);
            end
            pattern(((x-1)*n)+1:((x-1)*n)+n,((y-1)*n)+1:((y-1)*n)+n) = reshape(shuf_rates,n,n)';
        end
    end
end