#!/usr/bin/env python

import sys,os,code
from pprint import pprint
from topo import *

# set up the readline
try:
    import readline
except ImportError:
    print "Module readline not available.\nHistory and completion support disabled."
else:
    import rlcompleter
    readline.parse_and_bind("tab: complete")


# set the prompt and banner
sys.ps1 = 'Topographica> '

banner = """
Welcome to Topographica!
"""

#start the intepreter
interpreter = code.InteractiveConsole(locals())
interpreter.interact(banner)
