#!/usr/bin/env python

import sys,os,code
from pprint import pprint
from topo import *

# set up the interactive prompt
import rlcompleter,readline

readline.parse_and_bind("tab: complete")

sys.ps1 = 'Topographica> '

banner = """
Welcome to Topographica!
"""

interpreter = code.InteractiveConsole(locals())
interpreter.interact(banner)
