# $Id$
#
# Performs simple tests that the examples at least run; should be
# replaced by more extensive tests.

all: image_example gui_example cfsom_example lissom

cfsom_example:
	cd .. ; ./topographica examples/cfsom_example.py

gui_example:
	cd .. ; ./topographica examples/gui_example.py

image_example:
	cd .. ; ./topographica examples/image_example.py

lissom:
	cd .. ; ./topographica examples/lissom.ty




