# $Id$
#
# Performs simple tests that the examples at least run; should be
# replaced by more extensive tests.

all: image_example hierarchical cfsom_or lissom_or

cfsom_or:
	cd .. ; ./topographica examples/cfsom_or.ty

hierarchical:
	cd .. ; ./topographica examples/hierarchical.ty

image_example:
	cd .. ; ./topographica examples/image_example.py

lissom_or:
	cd .. ; ./topographica examples/lissom_or.ty




